### ISSUE TITLE
Text becoms upside down when using Arabic->utf8Glyphs

### ISSUE THREAD

**Issue by Sohib** [khaled-alshamaa/ar-php#15] opened 2021-06-29 12:24 UTC
This code snippet tells it all, the first part of this string become last part which make a sentence no readable. also it's adding `\n` at the end of each line which not exist at the original string, i have fixed this` $max` parameter to 300. 

if you notice `'السلام  '` was the in the bingeing  at the string but after using utf8Glyphs it become  the last one.

```php
use ArPHP\I18N\Arabic;


$arabic = new Arabic();
$str = "السلام عليكم في البداية نقولها وهذا نص رقم ١ و بعده نصين رقم ٢ و بعده نصات ٣ وبالنهاية لا نقول الا الحمدلله  حمدا كثيرا";

echo($arabic->utf8Glyphs($str,300));
/*
ﺍﺮﻴﺜﻛ ﺍﺪﻤﺣ  ﻪﻠﻟﺪﻤﺤﻟﺍ ﻻﺍ ﻝﻮﻘﻧ ﻻ ﺔﻳﺎﻬﻨﻟﺎﺑﻭ ٣   ﺕﺎﺼﻧ ﻩﺪﻌﺑ ﻭ ٢   ﻢﻗﺭ ﻦﻴﺼﻧ ﻩﺪﻌﺑ ﻭ ١   ﻢﻗﺭ ﺺﻧ ﺍﺬﻫﻭ ﺎﻬﻟﻮﻘﻧ ﺔﻳﺍﺪﺒﻟﺍ ﻲﻓ ﻢﻜﻴﻠﻋ ﻡﻼﺴﻟﺍ
*/
```

is there a way to fix the Glyphs without changing the order of the string?

**Comment by khaled-alshamaa** [comment] 2021-06-29 22:20
My dear friend Sohib, this is exactly what the utf8Glyphs method was developed to do in order to fix the simple Unicode rendering performed by GD and PDF libraries that does not support connecting glyphs of Arabic language and right-to-left writing direction properly (see issue examples [here](https://www.notarabic.com/)). It is not supposed to print out the output of that method using the echo function (there is no need as all browsers support Arabic glyphs and RTL languages very well).

On the other hand, the added new line character `\n` is the expected behavior because the default value of the `max_char` parameter is 50, and your string exceeded that limit, so the utf8Glyphs method injects it into your string to perform line-wrapping. For more information, please check the utf8Glyphs documentation [here](https://ar-php.org/github/docs/classes/ArPHP-I18N-Arabic.html#method_utf8Glyphs).

Finally, I am not aware of any use case that may need to perform the glyphs joining without reordering chars due to the lack of supporting right-to-left languages. If you have one, I will be more than happy to have a look at it and may add such an option to the library.

**Comment by Sohib** [comment] 2021-06-30 14:54
Thanks @khaled-alshamaa for responding so quickly.  im sorry i wasn't able to clarify this issue. 
i am using this library with [dompdf](https://github.com/dompdf/dompdf) and the text was't showing correctly for long lines. 

here is the code snippet to show the error 

```php
<?php

require 'vendor/autoload.php';


use Dompdf\Dompdf;
use Dompdf\Options;

function html2pdf($string)
{
    $options = new Options();
    $options->set('defaultFont', 'DejaVu Sans');

    // instantiate and use the dompdf class
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($string);
    // (Optional) Setup the paper size and orientation
    $dompdf->setPaper('A4', 'landscape');
    // Render the HTML as PDF
    $dompdf->render();

    // Output the generated PDF to Browser
    return $dompdf->stream();
}

$arabic = new \ArPHP\I18N\Arabic();
html2pdf($arabic->utf8Glyphs("السلام عليكم في البداية نقولها وهذا نص رقم ١ و بعده نصين رقم ٢ و بعده نصات ٣ وبالنهاية لا نقول الا الحمدلله  حمدا كثيرا"));

```

this will result the text to be displayed incorrectly like the following
<img width="1185" alt="Screen Shot 2021-06-30 at 5 51 56 PM" src="https://user-images.githubusercontent.com/5610514/123982894-14c5df80-d9cc-11eb-810d-b2e7d395f2f0.png">


its working correctly for short string but when using long lines it will display in wired order.

**Comment by khaled-alshamaa** [comment] 2021-07-05 13:12
My dear friend @Sohib, Dompdf is an HTML to PDF converter. So, you need to format your input in HTML probably in the first place. 

Therefore, after you set the maximum number of characters in every single line (i.e., the second parameter of the `utf8Glyphs` method, for example, 50), you need to call the `nl2br()` PHP function to replace all new line characters `\n` by break line tag `<br>`.

Also, to handle the right text alignment properly, you can use the HTML paragraph tag with an alignment property set to the right (e.g. `<p align="right">$arabicText</p>`).

I just alter the last two lines of your script like the following:
```php
$arabicText = $arabic->utf8Glyphs("السلام عليكم في البداية نقولها وهذا نص رقم ١ و بعده نصين رقم ٢ و بعده نصات ٣ وبالنهاية لا نقول الا الحمدلله  حمدا كثيرا", 
                                  50);

$arabicText = nl2br($arabicText);

html2pdf("<p align=\"right\">$arabicText</p>");
```
This will do the trick, and here is the example result:
![pdf](https://user-images.githubusercontent.com/11270404/124476588-4ad7da80-dda3-11eb-9918-2fb72b4ca462.png)

**Comment by khaled-alshamaa** [comment] 2021-07-05 21:05
Dear @Sohib, please close this issue if my answer above resolve your problem successfully ;-)

**Comment by Sohib** [comment] 2021-07-06 07:55
Thank for your help

**Closed** 2021-07-06 07:55 UTC

**Comment by badrshs** [comment] 2021-08-07 10:47
Hi @khaled-alshamaa , thanks a lot for this help. I'm still facing something similar to what @Sohib has , 
![image](https://user-images.githubusercontent.com/26596347/128597587-2d31bf2f-e8b9-46cd-a233-aee04b3f6624.png)

I'm using dompdf , and as you can see the first line start from the bottom to the top . any idea what casing that ?

**Comment by khaled-alshamaa** [comment] 2021-08-07 14:38
Hi @badrshs, Can you please share the code snippet that generates this output?
