### ISSUE TITLE
Unusual margin after using ar-php with Dompdf

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [khaled-alshamaa/ar-php#59] opened 2023-01-29 07:40 UTC
Hello Mr @khaled-alshamaa 

I am using [DomPdf](https://github.com/dompdf/dompdf) (especially the [Laravel version](https://github.com/barryvdh/laravel-dompdf)).

before using ArPHP the Arabic letters are separated:

![b713d22f-3dfc-4588-8cf6-665230f0805d](https://user-images.githubusercontent.com/24838274/215312121-9b8268f6-bb1b-4457-8713-882e6c6b6018.jpg)

After using the library the letters are fine but there is this initial margin:
![7acfab0c-8a32-4a8c-8013-391a5d4dbe1e](https://user-images.githubusercontent.com/24838274/215312169-7a2c3332-603a-4693-85e9-74ead5bbd1e9.jpg)

the code I am using from the library is: 

```
if ( ! class_exists( 'I18N_Arabic' ) ){
            $Arabic = new Arabic();
            $text = $Arabic->utf8Glyphs($text);
        }
}
```

If there any detail you want, tell me to provide it..

Thanks

**Comment by WatheqAlshowaiter** [comment] 2023-01-29 07:42
@al-saloul

**Comment by OmarASharaf** [comment] 2023-02-18 17:11
I have the same issue here. any solution?

**Comment by bsweeney** [comment] 2023-02-18 21:13
Is this a modification of the Dompdf source as suggested in dompdf/dompdf#712? The change proposed in that issue is not quite right. The width of the text frame has been determined before the modified logic, so the render positioning will be incorrect. Take a look at [this proposed change](https://github.com/dompdf/dompdf/pull/2107/files#diff-7e5d34094b1bc9a5a74a85fa5eb9aaf2e471879cd503f1f1b86a84a0b57d0a5fR308-R323) for a fairly decent modification to Dompdf related to text shaping. You would just need to replace tc-lib-unicode with ar-php in the referenced `bidi_transform` method.

Though it has problems for multi-line text, especially if there are inline elements.

**Comment by saifcloud** [comment] 2023-03-28 07:32
same issue please help us

**Comment by khaled-alshamaa** [comment] 2023-04-02 19:02
Can you please share the DomPdf code that you used to export this Arabic content processed via utf8Glyphs.

It will be super helpful at our side to reproduce this issue and figure out the reason behind that weird behavior or at least find a way to come over it, because I recall that I used this library before in some projects without any serious problems.. but still with some minor tricks.

**Comment by WatheqAlshowaiter** [comment] 2023-04-02 21:44
Hi Mr @khaled-alshamaa 

I have added this code in 

```php
if ( ! class_exists( 'I18N_Arabic' ) ){
            $Arabic = new Arabic();
            $text = $Arabic->utf8Glyphs($text);
        }
}

```
this line in the library 
https://github.com/dompdf/dompdf/blob/master/src/Renderer/Text.php#L74

**Comment by khaled-alshamaa** [comment] 2023-04-02 23:48
Hi my friend @WatheqAlshowaiter 

I am not that expert in Laravel framework, and still prefer the old school with a pure PHP flavor ;-)

Therefore, please find below an example that use DomPdf and Ar-PHP libraries to generate PDF file that presents Arabic content properly without any margin issue.

I simply provide the content in HTML format, then make use of the loadHtml function in the DomPdf library to generate the PDF output. I am sure that you will be able to alter this simple example into Laravel valid example to resolve your issue.

```php
require_once 'dompdf/autoload.inc.php';
require_once '../ar-php/src/Arabic.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();
$options->set('defaultFont', 'DejaVu Sans');

$dompdf = new Dompdf($options);
$arabic = new \ArPHP\I18N\Arabic();

$reportHtml = '
<html>
    <body>
        <div align="right">
            <p>تحديات عديدة تواجه حكومة ولد عبد الرحمن وتقف في طريق تنفيذ تعهدات رئيس الجمهورية التي اعلن عنها في حملته الدعائية الممهدة للانتخابات الرئاسية التي فاز بها قبل شهور من الان ولعل ابرز هذه التحديات تحدي الفساد النابع من سوء استخدام السلطة العامة من اجل مكاسب شخصية كاختلاس المال العام الذي عاد بقوة في المؤسسات العمومية والشركات وتفشي الرشوة في ادارات ومصالح الدولة حيث اصبح من الصعوبة بمكان ان تسحب مستخرجا من عقد ازدياد او بطاقة تعريف او شهادة وفاة من دون ان ترشي الحارس ثم البواب الذي يقف عند باب المكتب ثم المسؤول بطريقة فاضحة وهكذا.</p>
        </div>
    </body>
</html>';

$p = $arabic->arIdentify($reportHtml);

$maxLineChr = 80;
$htmlOutput = substr($reportHtml, 0, $p[0]);

for ($i = 0; $i < count($p); $i += 2) {
    $utf8ar = $arabic->utf8Glyphs(substr($reportHtml, $p[$i], $p[$i+1] - $p[$i]), $maxLineChr);
    $lastEn = isset($p[$i+2]) ? $p[$i+2] : strlen($reportHtml);

    $htmlOutput .= str_replace("\n", "<br>\n", $utf8ar);
    $htmlOutput .= substr($reportHtml, $p[$i+1], $lastEn - $p[$i+1]);
}

$dompdf->loadHtml($htmlOutput);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream('example', array('Attachment' => false));
```
![2023-04-03 01_46_55-example php](https://user-images.githubusercontent.com/11270404/229385540-0d0c741a-3705-4c32-9d11-cb2699b1ba7d.png)

I will highly appreciate your feedback after testing this code. Also, it will be great if you share a Laravel version of this example for others benefit.

**Comment by khaled-alshamaa** [comment] 2023-04-18 19:15
Dear @WatheqAlshowaiter, I check the sample code and the issue you reported in the following repository:
https://github.com/WatheqAlshowaiter/ar-php-dompdf

Well, it is not an issue related to the Ar-PHP library functionality. Even though, I will do you this favor regarding how to properly configure dompdf to load the background image and your custom font.

First, you have to replace [this line of code](https://github.com/WatheqAlshowaiter/ar-php-dompdf/blob/6753f4a54fe3f2ab4ae8aaf6f2ac0a798877f875/download-pdf.php#L10) by the following line:

```php
$options->set('isRemoteEnabled', true);
```

Then, make sure to use the absolute URL instead of relative path in both the CSS `url()` and image `src` attribute ;-)

Here is the resulted PDF on my local server for testing:
![2023-04-18 21_12_37-ةرﻮﺗﺎﻔﻟا](https://user-images.githubusercontent.com/11270404/232881506-e915b86b-c619-40e3-8625-3d236c81cffa.png)

**Comment by WatheqAlshowaiter** [comment] 2023-04-19 08:32
Hi Mr @khaled-alshamaa 

Thank you for your help.

I have followed your instructions but the result still the same!

you can check my sample code [here](https://github.com/WatheqAlshowaiter/ar-php-dompdf/blob/main/download-pdf.php).
I have made static absolute path for testing. anyone who want to use the code should modify it to his machine.


I don't know this is because of my machine or code

**Comment by khaled-alshamaa** [comment] 2023-04-19 10:41
Hi my friend @WatheqAlshowaiter,

I mentioned absolute URL not absolute path! Therefore, instead of something like:
```
/Users/watheq/Sites/htdocs/ar-dom-pdf/assets/cocon-next-arabic.ttf
```

You have to use the following:
```
http://localhost/ar-dom-pdf/assets/cocon-next-arabic.ttf
```

**Comment by WatheqAlshowaiter** [comment] 2023-04-19 11:15
My bad Mr @khaled-alshamaa 

It works fine now!

**Closed** 2023-04-19 11:35 UTC
