### ISSUE TITLE
Texts are not showing properly

### ISSUE THREAD

**Issue by shaycoder** [khaled-alshamaa/ar-php#55] opened 2022-12-13 12:50 UTC
I have Arabic text(html file) coming dynamically inside pdf using DomPdf and ar-php library.

I am just showing a line below in the $html variable but the text are not properly displaying, means they are not sorted altogether.

    require_once 'ar-php/src/Arabic.php';
    $Arabic = new ArPHP\I18N\Arabic();

    $html = "يقول الله عز وجل :(وكلوا واشربوا ولا تسرفوا إنه لا يحب المسرفين) الأعراف";

    $p = $Arabic->arIdentify($html);

    for ($i = count($p)-1; $i >= 0; $i-=2) {
        $utf8ar = $Arabic->utf8Glyphs(substr($html, $p[$i-1], $p[$i] - $p[$i-1]));
        $html   = substr_replace($html, $utf8ar, $p[$i-1], $p[$i] - $p[$i-1]);
    }
but its coming like لا يحب المسرفين) الأعراف يقول الله عز وجل :(وكلوا واشربوا ولا تسرفوا إنه

Pls any help would be appreciated.

**Comment by khaled-alshamaa** [comment] 2022-12-17 21:16
Dear @shaycoder,

I am not able to reproduce the issue you mentioned because you did not show where/how you output your `$html` content! I tried it with the GD library, and it works perfectly fine with no block miss ordering.

By the way, there is no need anymore for the complicated logic of handling/processing the `$p` array that you had in your example. Instead, all you have to do is the following code snippet. That logic is embedded internally in the utf8Glyphs method, but you may need to pass the second parameter of that function to increase the max number of characters you can fit in one line. For example:

```php
require_once 'ar-php/src/Arabic.php';
$Arabic = new ArPHP\I18N\Arabic();

$html = "يقول الله عز وجل :(وكلوا واشربوا ولا تسرفوا إنه لا يحب المسرفين) الأعراف";
$html = $Arabic->utf8Glyphs($html, 100);
```

**Comment by khaled-alshamaa** [comment] 2022-12-22 00:52
Dear @shaycoder, if I do not get any response from you within a couple of days, then I am sorry to close this ticket because we are not able to reproduce reported issue!

**Comment by shaycoder** [comment] 2022-12-22 07:49
`<style>
    body {
        margin: 0;
        padding: 0;
    }
    table {        
        border-collapse: collapse;
        width: 100%;
        box-sizing: border-box;
    }
    td, th {
        font-family: 'kfgqpc';
        text-align: right;
        padding: 8px;
    }
    @font-face {
        font-family: 'kfgqpc';
        src: url($src);
    }
    @font-face {
        font-family: 'LatoBold';
        src: url($src1);
        src: url($src1) format('embedded-opentype'),
            url($src2) format('woff2'),
            url($src3) format('woff'),
            url($src4) format('truetype'),
            url($src5) format('svg');
    }
    @font-face {
        font-family: 'LatoRegular';
        src: url($src6);
        src: url($src6) format('embedded-opentype'),
            url($src7) format('woff2'),
            url($src8) format('woff'),
            url($src9) format('truetype'),
            url($src10) format('svg');
    }
    @page { size: 320mm 320mm; margin: 40px;}
</style>
</head>
<body>
<table>
    <tr>
        <td style="font-size: 25px;text-align: center;padding: 25px 0;">
            <table>
                <tr>
                    <td style="font-size: 14px;text-align: left;padding: 0 25px; width: 30%;">
                        <img style="width:120px;margin-top: 8px;" src="' . $logo . '" />
                    </td>
                    <td style="font-size: 40px;text-align: center;padding: 0 25px; width: 40%;vertical-align: middle;">
                        <div style="line-height: 70px;font-family: LatoBold;">Diet Plan</div>
                    </td>
                    <td style="font-size: 16px;text-align: right;padding: 0 25px; width: 30%;">
                        <div style="font-family: LatoBold;line-height: 20px;color: #aeaeae">' . $contact_email . ' <img width="20" alt="" src="' . $img . '" /></div>
                        <div style="font-family: LatoBold;line-height: 20px;color: #aeaeae">Order #' . $order_id . '</div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>   

    <tr>
        <td style="font-size: 25px;text-align: center;padding: 25px 0;">
            <table style="background: #f2f2f2;padding: 20px 0;">
                <tr>
                    <td style="font-size: 16px;text-align: left;padding: 0 25px; width: 33.33%;vertical-align: top;">
                        <div><span style="font-family: LatoBold;font-weight: 700;">' . $total_kcal . '</span><span> : </span><span style="line-height: 25px;">أجمالي السعرات الحرارية </span></div>   
                        <div><span style="font-family: LatoBold;font-weight: 700;">' . $name . '</span><span> : </span><span style="line-height: 25px;">الأسم </span></div>
                    </td>
                    <td style="font-size: 16px;text-align: left;padding: 0 25px; width: 33.33%;vertical-align: top;">
                        <div><span style="font-family: LatoBold;font-weight: 700;">' . $age . '</span><span> : </span><span style="line-height: 25px;">العمر </span></div>   
                        <div><span style="font-family: LatoBold;font-weight: 700;">' . $weight . '</span><span> : </span><span style="line-height: 25px;">الوزن </span></div>
                        <div><span style="font-family: LatoBold;font-weight: 700;">' . $height . '</span><span> : </span><span style="line-height: 25px;">الطول </span></div>
                    </td>
                    <td style="font-size: 16px;text-align: left;padding: 0 25px; width: 33.33%;vertical-align: top;">
                        <div><span style="font-family: LatoBold;font-weight: 700;">' . $bmi . '</span><span> : </span><span style="line-height: 25px;">كتلة الجسم </span></div>   
                        <div><span style="font-family: LatoBold;font-weight: 700;">' . $state . '</span><span> : </span><span style="line-height: 25px;">الحالة </span></div>
                        <div><span style="font-family: LatoBold;font-weight: 700;">' . $email . '</span><span> : </span><span style="line-height: 25px;">البريد الألكتروني </span></div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td style="font-size: 25px;text-align: center;padding: 0;">
            <table style="padding:40px;">
                <tr>
                    <td style="font-size: 40px;text-align: center;padding: 0 25px;">
                        <div style="line-height: 70px;">' . $explanation_title . '</div>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 17px;text-align:right;padding: 0 25px; width: 33.33%;vertical-align: top;">
                        <div style="line-height: 70px;">' . $explanation_description . '</div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>`

Sir, this is my code(html) but I am not getting the html correctly in pdf, image not visible, number in the email showing ????, not aligned properly.

I have added the code suggested by you `$html = $Arabic->utf8Glyphs($html, 500);`

![Untitled](https://user-images.githubusercontent.com/11714271/209082226-e7fe75d4-f456-4899-b9d0-aae1281b0b40.png)

I get the pdf in english correctly
![1](https://user-images.githubusercontent.com/11714271/209082779-9f243f28-18ba-46c0-9abb-c5df9cc09e41.png)

**Comment by khaled-alshamaa** [comment] 2022-12-26 12:23
By looking at your code above, the issue is likely related to your HTML template. May you please try to alter this part:
```html
<div style="line-height: 70px;">' . $explanation_description . '</div>
```
By this one:
```html
<div style="line-height: 70px;" dir="rtl">' . $explanation_description . '</div>
```
Setting the value "rtl" (right-to-left) in the [`dir` attribute](https://www.w3schools.com/tags/att_global_dir.asp) of that `div` tag will let your PDF converter handle that text properly in terms of the [Bidi algorithm](https://unicode.org/reports/tr9/).

On the other hand, the issue of showing digits wrongly as ???? is most probably because the font you are using does not support the [Hindu form](https://en.wikipedia.org/wiki/Hindu%E2%80%93Arabic_numeral_system) of numbers (_Eastren Arabic numerals_). Therefore, either use a font that supports Hindu form digits (like [Amiri](https://www.amirifont.org/) font, for example) or till the `utf8Glyphs` method that you want to convert digits into Hindu form (the default behavior). You can do that using the following code snippet (_i.e., set the third parameter as false_):
```php
$html = $Arabic->utf8Glyphs($html, 500, false);
```
For more information, check the related documentation here.

**Comment by shaycoder** [comment] 2022-12-27 07:59
Thank you so much sir.
You are awesome!!!

**Comment by khaled-alshamaa** [comment] 2022-12-27 16:05
Did my suggested solution resolve both of your problems? Please confirm to close this issue successfully my friend :-)

**Comment by shaycoder** [comment] 2022-12-27 16:16
Yes sir, both issues are resolved.

Thank you

**Comment by khaled-alshamaa** [comment] 2022-12-27 16:49
You are most welcome my friend, I am glad to help :-)

**Closed by khaled-alshamaa** 2022-12-27 16:49 UTC
Labels: bug
